#' Convert a `tibble` to a mutation matrix
#'
#' A mutation matrix in this context is a gene x sample binary matrix.  The genes
#' reported in the rows will be limited by the specified `gene.list`.
#'
#' @param mut.tbl A `tibble` containing the following columns:
#'   `lab_id` -- Patient sample identifier
#'   `Gene` -- Gene symbol
#' @param gene.list Character vector of gene symbols that should overlap with the
#'   `Gene` values in `mut.tbl`
#' @returns A `length(gene.list)` x `length(unique(mut.tbl$lab_id))` binary matrix
make.mutation.mat <- function(mut.tbl, gene.list) {
  mut.genes <- select(mut.tbl, lab_id, Gene = symbol) %>%
    unique() %>%
    filter(Gene %in% gene.list) %>%
    mutate(
      mut = 1,
      lab_fac = factor(as.character(lab_id), levels = unique(as.character(mut.tbl$lab_id))),
      gene_fac = factor(Gene, levels = gene.list)
    )

  mut.tmat <- pivot_wider(mut.genes,
    id_cols = gene_fac, id_expand = T,
    names_from = lab_fac, names_expand = T, values_from = mut, values_fill = 0
  )

  mut.mat <- as.matrix(select(mut.tmat, -1))
  rownames(mut.mat) <- as.character(mut.tmat$gene_fac)

  mut.mat
}

#' Read in and convert TCGA GISTIC calls to a long `tibble`
#'
#' @param gistic.file Path to the TCGA GISTIC file
#' @returns a `tibble` containing the following columns:
#'   `Gene Symbol`
#'   `Locus ID`
#'   `Cytoband`,
#'   `barcode` -- TCGA sample barcode
#'   `call` -- GISTIC relative copy number value
process.gistic.calls <- function(gistic.file) {
  gistic.tbl <- readr::read_delim(gistic.file) %>%
    pivot_longer(cols = -c(1:3), names_to = "barcode", values_to = "call")


  gistic.tbl
}

#' Convert a `tibble` to a CNA matrix
#'
#' A CNA matrix in this context is a gene x sample numeric matrix.  The genes
#' reported in the rows will be limited by the specified `gene.list`.
#'
#' @param cna.tbl A `tibble` containing the following columns:
#'   `lab_id`-- Patient sample identifier
#'   `gene_name`-- Gene symbol
#'   `cent_cna` -- Relative copy number value (e.g. -2, -1, 0, 1, 2, ...)
#' @param gene.list Character vector of gene symbols that should overlap with the
#'   `gene_name` values in `cna.tbl`
#' @returns A `length(gene.list)` x `length(unique(mut.tbl$lab_id))` numeric matrix
#'   with each element containing the corresponding values `cent_cna` values.
make.cna.mat <- function(cna.tbl, gene.list) {
  cna.tbl <- filter(cna.tbl, gene_name %in% gene.list) %>%
    mutate(gene_fac = factor(gene_name, levels = gene.list))

  cna.tmat <- pivot_wider(cna.tbl,
    id_cols = gene_fac, id_expand = T,
    names_from = lab_id, values_from = cent_cna, values_fill = 0
  )

  cna.mat <- as.matrix(select(cna.tmat, -1))
  rownames(cna.mat) <- as.character(cna.tmat$gene_fac)

  cna.mat
}

#' Read in and preprocess a GDSC copy number matrix
#'
#' @param gdsc.cna.file A GISTIC file from GDSC: e.g.: cnv_gistic_20191101.csv
#' @param cl.list A character vector of cell line (model) identifiers
#' @param gene.list A character vector of gene symbols
#' @returns A `length(gene.list)` x `length(cl.list)` numeric matrix
make.gdsc.cna.mat <- function(gdsc.cna.file, cl.list, gene.list) {
  gdsc.cnas <- readr::read_delim(gdsc.cna.file)

  gdsc.cnas <- gdsc.cnas[-c(1:2), ]

  names(gdsc.cnas)[1:2] <- c("gene_id", "gene_name")

  gdsc.cnas <- filter(
    gdsc.cnas,
    gene_name %in% gene.list
  )

  g.cna.mat <- as.matrix(select(gdsc.cnas, -c(1:2)))
  g.cna.mat <- apply(g.cna.mat, 2, as.numeric)
  rownames(g.cna.mat) <- gdsc.cnas$gene_name

  common.cls <- intersect(cl.list, colnames(g.cna.mat))

  g.cna.mat[, common.cls]
}

#' Read in and process a GDSC alteration / drug association file
#'
#' @param drug.assoc.file File containing alteration /drug associations (e.g. TableS4C.xlsx)
#' @param drug.map A `tibble` that maps between HNSCC and GDSC drugs as generated by
#'   [map.gdsc.hnscc.drugs()]
#' @returns A `tibble` with the following columns:
#'   `FEATURE` -- The GDSC feature name for the alteration
#'   `type` -- Alteration type: Amp, Del, Mut infered from FEATURE name
#'      ('gain', 'loss' and '_mut' respectively)
#'   `Gene` -- Gene symbol
#'   `weight` -- Currently always 1.0
proc.gdsc.assoc.genes <- function(drug.assoc.file, drug.map) {
  drug.assoc <- readxl::read_excel(drug.assoc.file, skip = 37)

  use.assocs <- filter(drug.assoc, `Drug name` %in% drug.map$DRUG_NAME & Domain %in% c("PANCAN", "HNSC"))

  # mutations

  muts <- filter(use.assocs, grepl("_mut", FEATURE)) %>%
    select(FEATURE) %>%
    unique() %>%
    mutate(
      type = "Mut",
      Gene = sub("_mut", "", FEATURE)
    )

  # add CN amps

  amps <- filter(use.assocs, grepl("gain", FEATURE)) %>%
    select(FEATURE) %>%
    unique() %>%
    mutate(
      type = "Amp",
      Gene = str_match(FEATURE, "\\(([\\w,]+)\\)")[, 2]
    ) %>%
    separate_longer_delim(cols = Gene, delim = ",") %>%
    filter(is.na(Gene) == F)

  # ad CN dels

  dels <- filter(use.assocs, grepl("loss", FEATURE)) %>%
    select(FEATURE) %>%
    unique() %>%
    mutate(
      type = "Del",
      Gene = str_match(FEATURE, "\\(([\\w,]+)\\)")[, 2]
    ) %>%
    separate_longer_delim(cols = Gene, delim = ",") %>%
    filter(is.na(Gene) == F)

  assoc.tbl <- bind_rows(
    muts,
    amps,
    dels
  ) %>%
    mutate(weight = 1)

  assoc.tbl
}


# Adapted from http://dec2015.archive.ensembl.org/info/genome/variation/predicted_data.html#consequences
.mutation.order <- c(
  "splice_acceptor_variant", "splice_donor_variant", "stop_gained",
  "frameshift_variant", "stop_lost", "start_lost", "inframe_insertion", "inframe_deletion",
  "missense_variant"
)

# from `toupper` examples
.capwords <- function(s, strict = FALSE) {
  cap <- function(s) {
    paste(toupper(substring(s, 1, 1)),
      {
        s <- substring(s, 2)
        if (strict) tolower(s) else s
      },
      sep = "",
      collapse = " "
    )
  }
  sapply(strsplit(s, split = " "), cap, USE.NAMES = !is.null(names(s)))
}

#' Plot a mutation OncoPrint
#'
#' Create an OncoPrint summary heatmap of HNSCC gene mutations with mutation type
#' indicated by color. Genes are limited to those specified in `gene.list`.
#' The top portion of the plots displays a heatmap of clinical variables:
#' 'Disease Site', 'Smoking Status' and 'HPV Status'.  The right side of
#' the plot shows mutation frequency compared to TCGA-HNSC.
#'
#' @param mut.tbl A `tibble` containing the following columns:
#'   `lab_id`-- Patient sample identifier
#'   `Gene`-- Gene symbol
#' @param tcga.mut.freq.file An Excel file containing gene frequency info:
#'   `gene_name` -- Gene symbol
#'   `freq` -- Character values indicating frequencies (i.e. '10%')
#' @param clin A `tibble` containing clinical information with columns:
#'   `lab_id` -- Patient sample identifier
#'   `Smoking_Status` -- Smoker vs Non-smoker
#'   `Disease_Site` -- Anatomic site of tumor
#'   `HPV_Summary` -- Positive vs Negative
#' @param gene.list Character vector of gene symbols that should overlap with the
#'   `Gene` values in `mut.tbl`
#' @returns a PDF: 'figures/hnscc_mut_oncoprint.pdf'
make.mut.oncoprint <- function(mut.tbl, tcga.mut.freq.file, clin, gene.list) {
  mut.tbl <- mutate(mut.tbl, class_fac = factor(variant_classification,
    levels = .mutation.order, ordered = T
  ))

  mut.genes <- arrange(mut.tbl, class_fac) %>%
    filter(!duplicated(paste(lab_id, symbol))) %>%
    filter(symbol %in% gene.list) %>%
    mutate(
      lab_id = as.character(lab_id),
      gene_fac = factor(symbol, levels = gene.list)
    )

  mut.tmat <- pivot_wider(mut.genes,
    id_cols = gene_fac, id_expand = T,
    names_from = lab_id, values_from = variant_classification, values_fill = ""
  )

  char.mat <- as.matrix(select(mut.tmat, -1))
  rownames(char.mat) <- as.character(mut.tmat$gene_fac)

  # based on example from https://jokergoo.github.io/ComplexHeatmap-reference/book/oncoprint.html#apply-to-cbioportal-dataset

  col <- setNames(RColorBrewer::brewer.pal(length(.mutation.order), "Paired"), .mutation.order)

  alter_fun <- lapply(col, function(x) {
    alter_graphic("rect", fill = x)
  })

  alter_fun <- c(
    list(background = alter_graphic("rect",
      fill = "white", col = "black",
      horiz_margin = unit(0, "pt"),
      vertical_margin = unit(0, "pt")
    )),
    alter_fun
  )

  heatmap_legend_param <- list(
    title = "Mutations", at = .mutation.order,
    labels = .capwords(gsub("_", " ", .mutation.order)),
    border = F
  )

  use.clin <- filter(clin, lab_id %in% colnames(char.mat)) %>%
    mutate(`Smoking Status` = ifelse(Smoking_Status == "Lifelong Non-smoker", "Non-smoker", "Smoker")) %>%
    select(lab_id, `Disease Site` = Disease_Site, `Smoking Status`, `HPV Status` = HPV_Status) %>%
    as.data.frame()
  rownames(use.clin) <- use.clin$lab_id
  use.clin$lab_id <- NULL

  char.mat <- char.mat[, rownames(use.clin)]

  top.anno <- HeatmapAnnotation(
    df = use.clin,
    col = list(
      `Smoking Status` = c(Smoker = "red", `Non-smoker` = "lightgrey"),
      `HPV Status` = c(Positive = "red", Negative = "lightgrey"),
      `Disease Site` = setNames(RColorBrewer::brewer.pal(n = length(unique(clin$Disease_Site)), "Dark2"), unique(clin$Disease_Site))
    ),
    gp = gpar(col = "black")
  )

  tcga.mut.freq <- readxl::read_excel(tcga.mut.freq.file) %>%
    {
      setNames(.$freq, .$gene_name)
    }

  hnscc.mut.freq <- scales::percent(
    rowSums(char.mat != "") / ncol(char.mat),
    accuracy = 1
  )

  right.anno <- rowAnnotation(
    HNSCC = anno_text(hnscc.mut.freq[rownames(char.mat)], show_name = TRUE),
    TCGA = anno_text(tcga.mut.freq[rownames(char.mat)], show_name = TRUE),
    gap = unit(10, "points"), show_annotation_name = TRUE,
    annotation_name_side = "bottom"
  )

  ht <- oncoPrint(char.mat,
    alter_fun = alter_fun, col = col, top_annotation = top.anno,
    right_annotation = right.anno,
    show_pct = F, pct_side = "right", row_names_side = "left",
    remove_empty_columns = F, remove_empty_rows = T,
    heatmap_legend_param = heatmap_legend_param,
    alter_fun_is_vectorized = FALSE, show_column_names = T
  )

  pdf(file = "figures/hnscc_mut_oncoprint.pdf", width = 9, height = 3)

  draw(ht)

  dev.off()

  "figures/hnscc_mut_oncoprint.pdf"
}

#' Plot a CNA OncoPrint
#'
#' Create an OncoPrint summary heatmap of HNSCC gene CNAs with alteration type
#' indicated by color. Genes are limited to those specified in `gene.list`.
#' The top portion of the plots displays a heatmap of clinical variables:
#' 'Disease Site', 'Smoking Status' and 'HPV Status'.  The right side of
#' the plot shows CNA frequency compared to TCGA-HNSC.
#'
#' @param cna.tbl A `tibble` containing the following columns:
#'   `lab_id`-- Patient sample identifier
#'   `gene_name`-- Gene symbol
#'   `cent_cna` -- Relative copy number value (e.g. -2, -1, 0, 1, 2, ...)
#' @param clin A `tibble` containing clinical information with columns:
#'   `lab_id` -- Patient sample identifier
#'   `Smoking_Status` -- Smoker vs Non-smoker
#'   `Disease_Site` -- Anatomic site of tumor
#'   `HPV_Summary` -- Positive vs Negative
#' @param tcga.cna.tbl -- A `tibble` of TCGA CNA calls from GISTIC as produced
#'   by [process.gistic.calls()]
#' @param gene.list Character vector of gene symbols that should overlap with the
#'   `gene_name` values in `cna.tbl`
#' @returns a PDF: 'figures/hnscc_cna_oncoprint.pdf'
make.cna.oncoprint <- function(cna.tbl, clin, tcga.cna.tbl, gene.list) {
  cna.mat <- make.cna.mat(cna.tbl, gene.list)

  amp.mat <- ifelse(cna.mat >= 2, "AMP", "")

  del.mat <- ifelse(cna.mat <= -2, "HOMDEL", "")

  comb.cna.mat <- matrix(NA_character_,
    ncol = ncol(cna.mat), nrow = nrow(cna.mat),
    dimnames = list(rownames(cna.mat), colnames(cna.mat))
  )

  for (i in colnames(comb.cna.mat)) {
    comb.cna.mat[, i] <- ifelse(amp.mat[, i] != "" & del.mat[, i] != "",
      paste(amp.mat[, i], del.mat[, i], sep = ";"),
      comb.cna.mat[, i] <- paste0(amp.mat[, i], del.mat[, i])
    )
  }

  col <- c("HOMDEL" = "blue", "AMP" = "red")

  alter_fun <- list(
    background = alter_graphic("rect",
      fill = "white", col = "black",
      horiz_margin = unit(0, "pt"),
      vertical_margin = unit(0, "pt")
    ),
    HOMDEL = alter_graphic("rect", fill = col["HOMDEL"]),
    AMP = alter_graphic("rect", fill = col["AMP"])
  )

  heatmap_legend_param <- list(
    title = "Alterations", at = c("HOMDEL", "AMP"),
    labels = c("Deep deletion", "Amplification")
  )

  use.clin <- filter(clin, lab_id %in% colnames(comb.cna.mat)) %>%
    mutate(Smoking_Status = ifelse(Smoking_Status == "Lifelong Non-smoker", "Non-smoker", "Smoker")) %>%
    select(lab_id,
      `Disease Site` = Disease_Site, `Smoking Status` = Smoking_Status,
      `HPV_Status` = HPV_Status
    ) %>%
    as.data.frame()
  rownames(use.clin) <- use.clin$lab_id
  use.clin$lab_id <- NULL

  comb.cna.mat <- comb.cna.mat[, rownames(use.clin)]

  top.anno <- HeatmapAnnotation(
    df = use.clin,
    col = list(
      `Smoking Status` = c(Smoker = "red", `Non-smoker` = "lightgrey"),
      `HPV Status` = c(Positive = "red", Negative = "lightgrey"),
      `Disease Site` = setNames(RColorBrewer::brewer.pal(n = length(unique(clin$Disease_Site)), "Dark2"), unique(clin$Disease_Site))
    ),
    gp = gpar(col = "black"), show_legend = F
  )

  tcga.cna.freq <- tcga.cna.tbl %>%
    filter(abs(call) > 1 & `Gene Symbol` %in% rownames(comb.cna.mat)) %>%
    summarize(n = n(), .by = `Gene Symbol`) %>%
    mutate(
      total = length(unique(tcga.cna.tbl$barcode)),
      perc = scales::percent(n / total, accuracy = 1)
    ) %>%
    {
      setNames(.$perc, .$`Gene Symbol`)
    }

  hnscc.cna.freq <- scales::percent(
    rowSums(comb.cna.mat != "") / ncol(comb.cna.mat),
    accuracy = 1
  )

  right.anno <- rowAnnotation(
    HNSCC = anno_text(hnscc.cna.freq[rownames(comb.cna.mat)], show_name = TRUE),
    TCGA = anno_text(tcga.cna.freq[rownames(comb.cna.mat)], show_name = TRUE),
    gap = unit(10, "points"), show_annotation_name = TRUE,
    annotation_name_side = "bottom"
  )


  ht <- oncoPrint(comb.cna.mat,
    alter_fun = alter_fun, col = col, top_annotation = top.anno,
    right_annotation = right.anno,
    show_pct = F, pct_side = "right", row_names_side = "left",
    remove_empty_columns = F, remove_empty_rows = T,
    heatmap_legend_param = heatmap_legend_param,
    alter_fun_is_vectorized = FALSE, show_column_names = T
  )

  pdf(file = "figures/hnscc_cna_oncoprint.pdf", width = 5, height = 4)

  draw(ht)

  dev.off()

  "figures/hnscc_cna_oncoprint.pdf"
}
